name: Check Code Coverage

on: [pull_request]

jobs:
  check-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Tools
      run: |
        go get github.com/t-yuki/gocover-cobertura
        go get github.com/Boskey/cobertura-calculate

    - name: Run Tests and Generate Coverage Report
      run: |
        go test -coverprofile=coverage.out ./...
        gocover-cobertura < coverage.out > coverage.xml

    - name: Check Code Coverage
      run: |
        threshold=80
        coverage=$(cobertura-calculate -i coverage.xml -m coverage -o text)
        if (( $(echo "$coverage >= $threshold" | bc -l) )); then
          echo "Code coverage is $coverage%, meets the required threshold."
        else
          echo "Code coverage is $coverage%, below the required threshold. Please improve the code coverage."
          exit 1
        fi
      
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
